### ISSUE TITLE
Failure on AcmCertificateStack

### ISSUE THREAD

**Issue by rdurnin** [aws-samples/amazon-cloudfront-secure-static-site#22]
This template fails for me consistently during the nested AcmCertificateStack (DomainValidationRecord CREATE_COMPLETE). It looks as though the DNS validation for the certificate hangs indefinitely (using root or an elevated admin account and from us-east1). In the certificate manager UI the new certificate's Validation Signature remains in a pending state until the stack fails completely and cleans out the entries.

**Comment by ZacharyRSmith** [comment]
I had a similar issue. I forgot to add `.com` to my DomainName

**Comment by rdurnin** [comment]
Hey Zachary, and thanks for answering my question. The issue I was having was related to DNS NS records generated by Route 53 pointing to different name servers than those used by the domain I registered using Route 53. 

([Solution](https://forums.aws.amazon.com/thread.jspa?threadID=241023): Answer is somewhere near where user donblair chimes in)

**Comment by ConnorKirk** [comment]
Looks like your issue got solved. I'm going to close this for now.

**Comment by chriszrc** [comment]
@ConnorKirk that link is dead, I just ran this cloudformation using all the basic defaults, and had the exact same problem, CREATE_FAILED on the nested certificate step :(

**Comment by chriszrc** [comment]
Is there no way to mark fields required for these stacks? I left out the HostedZoneId, that's why it failed:

<img width="969" alt="Screenshot 2023-10-27 at 9 51 18 PM" src="https://github.com/aws-samples/amazon-cloudfront-secure-static-site/assets/25695785/90416001-ccf8-4c90-92a4-704e5b52d466">
