### ISSUE TITLE
How can I use Apex/Naked domain instead of www (sub domain name)?

### ISSUE THREAD

**Issue by bugb** [aws-samples/amazon-cloudfront-secure-static-site#24]
The stack work perfect but how can I use Apex/Naked domain instead of www (sub domain name)?

**Comment by ultimaweapon** [comment]
I guess this is what you are looking for: https://github.com/aws-samples/amazon-cloudfront-secure-static-site/pull/30

**Comment by bugb** [comment]
Thank @ultimaweapon . Closed
