### ISSUE TITLE
Update to use native certificate provider

### ISSUE THREAD

**Issue by dustin-rcg** [aws-samples/amazon-cloudfront-secure-static-site#28]
This solution currently uses a custom provider https://github.com/binxio/cfn-certificate-provider , which is now deprecated as noted in its README. Please update to create the certificate in certificate manager directly from CloudFormation instead of using the custom provider.

**Comment by ConnorKirk** [comment]
I'm pleased to say this is now implemented. Thanks for opening an issue @dustin-rcg
