### ISSUE TITLE
Function Updates are not Deployed?

### ISSUE THREAD

**Issue by MarkHerhold** [aws-samples/amazon-cloudfront-secure-static-site#37]
It seems that I have to re-associate a function with CloudFormation manually after every code update for it to actually take effect. 
Is there a way to automate this?

**Comment by ConnorKirk** [comment]
Hi @MarkHerhold 
Thanks for opening an issue.

This page on [Editing a Lambda@Edge function associated with a CloudFront Distribution](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-edit-function.html) explains the process better than I will.

In summary, a new version of the Lambda @ Edge function needs to be published. The trigger for the Lambda@Edge function then needs to be created.

The new version of this sample no longer includes a Lambda@Edge function for adding security headers. These are now configured using [CloudFront Response Header Policies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-response-headers.html)
