### ISSUE TITLE
doesn't allow an ajax call to api gateway

### ISSUE THREAD

**Issue by JonnyOrtiz-source** [aws-samples/amazon-cloudfront-secure-static-site#38]
I updated the content security policy in index.js to allow an api gateway invoke url as a connect-src but it blocks it. I changed the default-src to * and tried again but it still blocks it. Here's an example of the csp:

headers['content-security-policy'] = [
        {
            key: 'Content-Security-Policy',
            value: "frame-ancestors 'self'; block-all-mixed-content; default-src *; script-src 'self'; style-src 'self'; object-src 'self'; frame-src 'self'; child-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self'; manifest-src 'self'; base-uri 'self'; form-action 'self'; media-src 'self'; prefetch-src 'self'; worker-src 'self';",
        },

**Comment by ConnorKirk** [comment]
Hi Jonny,
Can you give an example of the Content Security Policy that wasn't working for you?

Here's an example of a policy that allows connection to API Gateway and Cognito

```js
"content-security-policy": [
            {
                key: "Content-Security-Policy",
                value: "default-src 'none'; connect-src https://*.execute-api.eu-central-1.amazonaws.com https://*.auth.eu-central-1.amazoncognito.com; font-src data:; img-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self'",
            },
        ],
```

**Comment by JonnyOrtiz-source** [comment]
Hi Connor.  Here’s the last iteration of the CSP I tried before giving up:

{
            key: 'Content-Security-Policy',
            value: "frame-ancestors 'self'; block-all-mixed-content; default-src *; script-src 'self'; style-src 'self'; object-src 'self'; frame-src 'self'; child-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self' https://ovvpbdmxqd.execute-api.us-east-1.amazonaws.com/prod/contactus; manifest-src 'self'; base-uri 'self'; form-action 'self'; media-src 'self'; prefetch-src 'self'; worker-src 'self';",
        }

**Comment by ConnorKirk** [comment]
Thanks for the example Jonny.
I can't spot an obvious problem with the CSP. One suggestion is to try removing the path in the `connect-src`. The CSP standard expects a domain, rather than a full URL. 

i.e. 
Domain: `https://ovvpbdmxqd.execute-api.us-east-1.amazonaws.com/` 
URL: ` https://ovvpbdmxqd.execute-api.us-east-1.amazonaws.com/prod/contactus`


Updated CSP
```
{
            key: 'Content-Security-Policy',
            value: "frame-ancestors 'self'; block-all-mixed-content; default-src *; script-src 'self'; style-src 'self'; object-src 'self'; frame-src 'self'; child-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self' https://ovvpbdmxqd.execute-api.us-east-1.amazonaws.com/; manifest-src 'self'; base-uri 'self'; form-action 'self'; media-src 'self'; prefetch-src 'self'; worker-src 'self';",
}
```
