### ISSUE TITLE
Use CloudFront response header policy instead of Lamda@Edge

### ISSUE THREAD

**Issue by thomasturrell** [aws-samples/amazon-cloudfront-secure-static-site#40]
CloudFront now supports [response header policies](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-cloudfront-supports-cors-security-custom-http-response-headers/).

With the introduction of response header policies there is no need to use Lamda@Edge to add security headers.

Unlike Lamda@Edge CloudFront response headers policies do not have an additional cost.

**Comment by ConnorKirk** [comment]
I'm pleased to say this is now implemented. Thanks for opening an issue @thomasturrell
