### ISSUE TITLE
ACM Domain Validation not Automatic for "Apex" Record

### ISSUE THREAD

**Issue by alexblanck** [aws-samples/amazon-cloudfront-secure-static-site#53]
When creating the stack with `CreateApex` set to `yes` and `HostedZoneId` set correctly, I observed that CNAME validation records were only created for the subdomain record and not for the apex record. 

I believe this is because the template only provides `DomainValidationOptions` for the subdomain: https://github.com/aws-samples/amazon-cloudfront-secure-static-site/blob/master/templates/acm-certificate.yaml#L29

**Comment by ConnorKirk** [comment]
Hi Alex,
Thanks for opening an issue

I'm investigating and will get back you

**Comment by ConnorKirk** [comment]
This should now be fixed. Thanks again Alex.
