### ISSUE TITLE
Info required for witch file

### ISSUE THREAD

**Issue by ammar-khan** [aws-samples/amazon-cloudfront-secure-static-site#59]
Appreciate the amazing example shared by the community and contributors 

I need to ask a question about witch file which is used as lambda, but I am not able to get the purpose and why this file is required?

Also do you have a python alternate of this file?

Thanks

**Comment by ConnorKirk** [comment]
Hi Ammar, thanks for opening an issue.

The `witch.js` file defines a AWS CloudFormation Custom resource handler. This handler is executed when deploying the cloudformation template. The purpose of the custom resource is to upload the contents of the static site to the S3 Bucket.

The function traverses the `/www` directory and uploads each file to the S3 bucket specified. I don't have a python equivalent of this custom resource.

**Comment by ammar-khan** [comment]
Thanks @ConnorKirk 

Really appreciate your timely and helpful response

Great resource and very helpful contributions by you all

**Comment by IanLondon** [comment]
Why is it called `witch`? :mage_woman: Is it an acronym or something, or is it just for fun?

**Comment by ConnorKirk** [comment]
@stilvoid has the authoritative answer
