### ISSUE TITLE
Failure to create `S3BucketLogs`

### ISSUE THREAD

**Issue by JLErvin** [aws-samples/amazon-cloudfront-secure-static-site#60]
In April 2023, Amazon automatically enabled S3 Block Public Access and disabled access control lists for all new buckets. When attempting to perform the `aws cloudformation deploy ...` step in this example, custom resources will always fail to create the `S3BucketLogs` due to this change.

I was able to get the example working by providing the following diff:
```diff
-      AccessControl: LogDeliveryWrite
+      OwnershipControls:
+        Rules:
+          - ObjectOwnership: ObjectWriter
```

Which was suggested per this AWS [blog post](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/). It's unclear to me if the maintainers of this library want to implement that solution, but the example currently does not work as-is.

**Comment by ConnorKirk** [comment]
This is now fixed. I'm sorry for the delay. Thank you again for raising the issue.
