### ISSUE TITLE
Migrate OAI to OAC?

### ISSUE THREAD

**Issue by amelluk** [aws-samples/amazon-cloudfront-secure-static-site#63]
It seems that OAI authentication is now being deprecated in favour of OAC. Will there be an update for this accommodating OAC? As per https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by ConnorKirk** [comment]
Thanks for the suggestion. I've done this.
