### ISSUE TITLE
Bump to Node20

### ISSUE THREAD

**Issue by nicholasphair** [aws-samples/amazon-cloudfront-secure-static-site#71]
Hi all, 

Node 16 has reached end-of-life and it is [recommend to bump to node 20][1].

> Runtime deprecation for Node.js 16
>
> In response to customer feedback, AWS is delaying the deprecation of the Node.js 16 runtime until 9 months after the end of community LTS. The Node.js 16 runtime will be deprecated on the date provided in the Supported Runtimes table. As stated in the preceding note, between the end of LTS on September 11, 2023 and the deprecation date, Lambda will only apply OS patches to the runtime. No security patches for the language runtime will be applied during this period.
>
> Delaying the deprecation of Node.js 16 gives customers using this runtime the opportunity to migrate their functions directly to Node.js 20, skipping Node.js 18.

[1]: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

**Comment by ConnorKirk** [comment]
Thanks for opening this issue!
